# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flagify < Formula
  desc "Flagify CLI — manage feature flags from the terminal"
  homepage "https://flagify.dev"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.2/flagify_darwin_amd64.tar.gz"
      sha256 "39ff39e372769f374dfa4c7afb054dfd0e445b2a272e6f7fd72e2cc05dd40d17"

      define_method(:install) do
        bin.install "flagify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.2/flagify_darwin_arm64.tar.gz"
      sha256 "151fe32ba290865223ac5a2bc0d48a5d0291328be1f2e9aec44baa5189d51fe8"

      define_method(:install) do
        bin.install "flagify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.2/flagify_linux_amd64.tar.gz"
      sha256 "f9b304b372305b50520596ed852a8b01a23a85e0745f2c030d7d3984af19ff11"
      define_method(:install) do
        bin.install "flagify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.2/flagify_linux_arm64.tar.gz"
      sha256 "26d515be85b0f255db23d8ce4f345d0c3c03e380dca46a0edeb38a9fce9e1d26"
      define_method(:install) do
        bin.install "flagify"
      end
    end
  end

  test do
    system "#{bin}/flagify", "version"
  end
end
