# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flagify < Formula
  desc "Flagify CLI — manage feature flags from the terminal"
  homepage "https://flagify.dev"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.1/flagify_darwin_amd64.tar.gz"
      sha256 "b95e70071d53e18a46817d9a5cfd110e6c51013afb5237f48c7c766e5e7d8822"

      define_method(:install) do
        bin.install "flagify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.1/flagify_darwin_arm64.tar.gz"
      sha256 "0e23195e635ce988a74c85dcebc88bb532eec587e554c8073c02ffa4e9331ed6"

      define_method(:install) do
        bin.install "flagify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.1/flagify_linux_amd64.tar.gz"
      sha256 "115a504e28318079bd80a360b0d730abec3e9e134d03944a436827687fc06abe"
      define_method(:install) do
        bin.install "flagify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagifyhq/cli/releases/download/v0.0.1/flagify_linux_arm64.tar.gz"
      sha256 "3141468a2c0bd71b0f3d320dd0e6796dcc488912d19638efe6cf857e502368c3"
      define_method(:install) do
        bin.install "flagify"
      end
    end
  end

  test do
    system "#{bin}/flagify", "version"
  end
end
